import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/sonner"
import {AppProvider} from "@/hooks";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'User send message',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <AppProvider>
        {children}
      </AppProvider>
      <Toaster />
      </body>
    </html>
  )
}
